### ISSUE TITLE
Not working on 2018.2.8f1

### ISSUE THREAD

**Issue by MostHated** [zulfajuniadi/unity-ecs-navmesh-mapbox#2]
Hello,
    I wanted to give this a go so I could see how all this ECS and job stuff works but when I imported this I just get a ton of errors. I made sure the right packages were installed and what not. Is there a compatibility issue with 2018.2.8f1?

Thanks,
-MH

**Comment by MostHated** [comment]
A example is in DemoSystems.cs -  protected override void OnCreateManager (int capacity) is saying that there is no method to override, I go look at OnCreateManager() in ComponentSystem.cs and it just has this

```
        /// <summary>
        ///     Called when the ScriptBehaviourManager is created.
        ///     When a new domain is loaded, OnCreate on the necessary manager will be invoked
        ///     before the ScriptBehaviour will receive its first OnCreate() call.
        /// </summary>
        protected virtual void OnCreateManager()
        {
        }
```

Edit ---- I went back and tried it again with a fresh project using 2018.2.7f1 and it worked just fine, my apologies. I guess they must have changed something in 2018.2.8f1.

**Comment by zulfajuniadi** [comment]
Thanks for that, I'll try it out on 2018.2.8. I'm not even sure if it'll run on the entities package > preview.8

**Comment by MostHated** [comment]
---- Edit, after I wrote all that, I spent a few minutes looking around more at your data structure and realized I am essentially going to have to remake my entire system, which is perfectly fine, but sort of defeats the whole long post I made, lol. Sorry about wasting your time with a long read!

No worries my man. Some companies like to introduce game changers, Unity like to throw out game breakers, lol. As I mentioned it seems to be working just fine for me on 7, so, for the time being, I can just take a look at that. 

Do you mind if I ask you a few questions about your project? You seem to have this down quite well. I could use a few pointers as this is my first time trying to use the new stuff.

I already have my own pathfinding implementation as well as movement, I was trying to find something I could look at to see if I could convert what I already have to use ECS and the job system, it seems a bit more complex than I was originally expecting it to, lol. I mean, it doesn't seem terrible. I return my path just as a "WaypointPath" object which contains a list of vector3's but I am not quite sure how I would implement it in comparison to your system. I see you have :  

        private struct AgentData
        {
            public int index;
            public Entity entity;
            public NavAgent agent;
        }

The way I have mine set up is each NPC character and vehicle has a script on them called PedestrianMover and VehicleMover respectively. Other than that the NPC's are just a renderer, some colliders, etc.

This is essentially what I am working with to handle the movement, the pedestrian, of course, is just missing the wheels, but I added in a random idle time at the end of each completed path cycle so they can rest for a minute, lol. 
https://i.imgur.com/laaRGhF.png

In the case of the struct you have, if I were going to implement similar to what you have but using waypoints and movement that is pretty simple, but I really like how it came out just using this (the wheels get thrown in there and just spin at a consistent rate) : 

		void Move()
		{
			vehicle.position += vehicle.forward * speed * Time.deltaTime;
			RotateTowardsDest(currentWaypoint.transform.position);

			foreach (GameObject wheel in wheels)
			{
				var spin =	wheel.GetComponent<Transform>();
				spin.Rotate(spinSpeed / 60 * 360 * Time.deltaTime, 0, 0);
			}
		}

		void RotateTowardsDest(Vector3 dest)
		{
			var targetDir = Vector3.zero;
			targetDir = ignoreY ? new Vector3(dest.x, vehicle.position.y, dest.z) : dest;
			Quaternion rotation = Quaternion.LookRotation(targetDir - vehicle.position);
			vehicle.rotation = Quaternion.Slerp(vehicle.rotation, rotation, Time.deltaTime * currentTurnSpeed);
		}

In this case, do I just do similar to what you did with the NavAgent, I would just use either the VehicleMover or PedestrianMover classes instead? I am thinking that mine probably would not have to be as complex, as I really am only using the things below: 
After all the waypoints are gathered into a list, the character runs this which picks one of the waypoints
    public Waypoint GetRandomWaypoint(string type = null)

Then it runs this to actually determine the path and return the vector3's, and then the character begins on his way.
     public WaypointPath GetPath(Waypoint start, Waypoint goal, bool unblocked = true)

Looking back just now at what I wrote, I realize I kind of just threw a bunch of stuff out there that doesn't really make sense, lol, I do apologize. I guess what I am getting at is do you happen to have a quick recommendation on where the best place to start would be in trying to take what I currently have and making it similar to yours? As I mentioned, it seems like dropping off the NavAgent and replacing it with one of my mover classes would be what I need to do, at the same time I am not sure if that type of class can be included in a struct, and maybe I need something more simple like just the WaypointPath vector list to go into that struct?

If what I asked doesn't make sense,  It's mostly because I don't even really know what I should be asking. So no worries if there is no good answer. I will probably just end up trying everything under the sun until I finally get a combination that works, lol.

**Comment by zulfajuniadi** [comment]
>  I return my path just as a "WaypointPath" object which contains a list of vector3's but I am not quite sure how I would implement it in comparison to your system.

Basically how this package works is it get's a bunch of polygon IDs from Unity's c++ backend and calculates the best path from that list of polygons into waypoints. The agent will visit those waypoints one at a time until there's none left to visit. Then requests another path from the navmesh system.

> I already have my own pathfinding implementation as well as movement, I was trying to find something I could look at to see if I could convert what I already have to use ECS and the job system

I suppose you could hook up the your own pathfinding algorithm to handle the pathfinding logic and build the way points that way. You might want to store those waypoints into a `NativeQueue<float3>` since the Job system won't handle anything **but** blittable data types in structs. You might need to look into re-implement the functionalities you'd need in ECS. Even the basic stuff like collision are not available in ECS, you'll have to do that yourself.

For the movement, I would suggest the Pedestrian and Vehicle mover be two different systems that does the movement logic for the respective entities as the rules of movement are different.

It looks to me that you're using Unity's built in components too - you can't use those with the ECS JobSystem since it doesn't handle classes. Everything is pretty much DIY at this point.

> I guess what I am getting at is do you happen to have a quick recommendation on where the best place to start would be in trying to take what I currently have and making it similar to yours?

I would start from a clean slate. Migrate the pathfinding algorithm to use structs instead of classes so it can be handled by the jobsystem. Once you have the waypoints, then do the movement. Also, profile early, profile often. You'd be surprised on the amount of code you thought were performant, but is actually a performance nightmare.

Feel free to contact me via Discord and we could have a further chat into this. I'm usually lurking in the [Unity Developer Hub](https://discord.gg/kbmWwpz) server. My username there is Hail Burns.

Good luck :)

**Comment by MostHated** [comment]
Awesome info man, I really appreciate it. I somewhat figured that a complete redo was probably necessary, so that is what I had started on as soon as I finished writing that, lol. I believe I am in that server already, I just don't make my way into it very often. I will give it more of a go tomorrow and she what I can come up with, then if I run into any snags I will give you a shout. 

Have a good weekend and thanks again,
-MH
